In [1]:
import numpy as np

a = np.array([1,2,3])
print(a)

[1 2 3]


In [3]:
b = np.array([[1,2,3],
             [4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [9]:
c = np.array([[[1,2,3],[5,6,5]],
              [[4,5,6],[6,8,7]]])
d = np.array([[[1,2,3],[5,6,7],
               [6,7,8],[9,10,11]]])
print(c)

[[[1 2 3]
  [5 6 5]]

 [[4 5 6]
  [6 8 7]]]


In [11]:
m = np.array([1,2,3],dtype=int)


2011230792048

In [15]:
np.arange(99).reshape(33,3)

(array([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23],
        [24, 25, 26],
        [27, 28, 29],
        [30, 31, 32],
        [33, 34, 35],
        [36, 37, 38],
        [39, 40, 41],
        [42, 43, 44],
        [45, 46, 47],
        [48, 49, 50],
        [51, 52, 53],
        [54, 55, 56],
        [57, 58, 59],
        [60, 61, 62],
        [63, 64, 65],
        [66, 67, 68],
        [69, 70, 71],
        [72, 73, 74],
        [75, 76, 77],
        [78, 79, 80],
        [81, 82, 83],
        [84, 85, 86],
        [87, 88, 89],
        [90, 91, 92],
        [93, 94, 95],
        [96, 97, 98]]),
 8)

In [39]:
p = np.arange(16).reshape(2,2,2,2)
print(p)
p[1][0]
p[0] [0] 
p[0:1:1,0:1:1]

[[[[ 0  1]
   [ 2  3]]

  [[ 4  5]
   [ 6  7]]]


 [[[ 8  9]
   [10 11]]

  [[12 13]
   [14 15]]]]


array([[[[0, 1],
         [2, 3]]]])

In [40]:
np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [41]:
np.arange(16).reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [44]:
p = np.arange(16).reshape(2,2,2,2)
p

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

In [53]:
p[0][1][::]

array([[4, 5],
       [6, 7]])

In [ ]:
# p[1][0]

import numpy as np

arr = np.array([
    [[10, 11], [12, 13]],     # Page 0
    [[20, 21], [22, 23]],     # Page 1
    [[30, 31], [32, 33]]      # Page 2
])
# [[[10, 11],
# [12, 13]],

#[[20, 21],
#[22, 23]],

#[[30, 31],
# [32, 33]]])

# print(arr[2, 1, 0])
# print(arr[:,0,:])
# print(arr[1])
# print(arr[2,1,0])
# print(arr[1,1,1])
# print(arr[:,0,:])
# print(arr[2:,:].flatten())
# print(arr[:,:,1].flatten())
print(arr[:,0,1])

In [16]:
import numpy as np

arr = np.array([
    [[10, 11], [12, 13]],     # Page 0
    [[20, 21], [22, 23]],     # Page 1
    [[30, 31], [32, 33]],
    [[34, 35], [36, 37]],
    [[38, 39], [40, 41]]          # Page 2
])
# [[[10, 11],
#   [12, 13]],

#   [[20, 21],
#   [22, 23]],

#   [[30, 31],
#   [32, 33]],

#   [[34, 35],
#   [36, 37]],

#   [[38, 39],
#   [40, 41]]])

# arr[0:2,1,1]
# arr[2].flatten()
# arr[:,1,0]
# arr[2:,1,1:]
arr[3,0,1]


np.int64(35)