In [1]:
import time
print("heloo")

time.sleep(2)

print("here we go!")

heloo
here we go!


In [2]:
import random
import string
def generate():
    length = int(input("Enter password lngth: "))
    if length < 4:
        print("Password length should be at least more than 4!")
        return
    character = string.ascii_letters + string.digits + string.punctuation
    password = ''.join(random.choices(character, k=length))
    print("Generated password:", password)

generate()

Generated password: `JlM^vo2;f/a}OrVu6e9Z*


In [3]:
def otp():
    r = random.randint(1000,9999)
    return r

print("Your OTP (Dont Share With Anyone!):",otp())


Your OTP (Dont Share With Anyone!): 9324


In [4]:
import uuid
import random

# def uid():
#     uuid.uuid1()

# def 

r = uuid.uuid1()
t = uuid.uuid4()
print(r)
print(t)


53070398-46b5-11f0-b310-d8f2ca483a9f
772143b5-a264-42a8-bc0f-607ea9296576


In [ ]:
# import math
# text = input("enter dir module name: ")
# if text.lower() == "Math":
#     print(dir(math))
# else:
#     print("somenthing went wrong!")
try:
    module_name = input("Enter module name to explore: ")
    module = __import__(module_name)
    print(dir(module))
except ModuleNotFoundError:
    print("Enter valid module name!!")


Enter valid module name!!


In [6]:
import numpy as np
Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [7]:
n = np.unravel_index(100,(6,7,8))
n


(np.int64(1), np.int64(5), np.int64(4))

In [8]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


In [ ]:
import numpy as np
def arr1():
    x = int(input("enter row: "))
    y = int(input("enteer columns: "))
    sure = x*y

    elements = input(f"Enter {sure} numbers: ").split()
    elements = [int(i) for i in elements]

    if len(elements)!=sure:
        print("enter in proper format in",{sure})
    else:
        arr = np.array(elements).reshape(x,y)
        print("Original array: ")
        print(arr)
    return arr

def arr2():
    a = int(input("enter row: "))
    b = int(input("enteer columns: "))
    suree = a*b

    elementss = input(f"Enter {suree} numbers: ").split()
    elementss = [int(j) for j in elementss]

    if len(elementss)!=suree:
        print("enter in proper format in",{suree})
    else:
        arrr = np.array(elementss).reshape(a,b)
        print("Second array: ")
        print(arrr)
    return arrr




while True:
    print("1. add")
    print("2. split")
    print("3. search")
    print("4. exit")
    g = input("enter a choice")
    match g:
        case '1':
            j = arr1()+arr2()
            print("your addition: ")
            print(j)

        case '2':
            v = np.concatenate([arr1(),arr2()])
            print(v)
        case '3':    
            a = arr1()
            search = int(input("Enter a value to search: "))
            # search = (int(x) for x in search).split()
            if search in a:
                print("="*30)
                print("yess we found it")
                print(search)
                print("="*30)
            else:
                print("Not found!")
                print("="*30)

        case '4':
            a = arr1()
            print

        case '5':
            break


1. add
2. split
3. search
4. exit


Original array: 
[[1 2 3 4]
 [5 4 3 5]
 [6 7 6 5]
 [4 5 6 7]
 [8 9 1 2]]
yess we found it
2
1. add
2. split
3. search
4. exit


In [5]:
x = int(input("enter row: "))
y = int(input("enteer columns: "))
z = int(input("enter number of box in the array: "))
s = x*y*z
elements = input(f"enter {s} elements of 3d array: ").split()
elements = [int(i) for i in elements]

arr = np.array(elements).reshape(x,y,z)
print("2D array is:")
print(arr)

v = np.vsplit(arr)
print(v)


2D array is:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


TypeError: vsplit() missing 1 required positional argument: 'indices_or_sections'

In [24]:
r = int(input("enter row: "))
c = int(input("enter col: "))
d = r*c
elements = input(f"Enter total elements {d}").split()
elements = [int(x) for x in elements]
i = np.array(elements).reshape(r,c)
d = np.sort(i,axis=0)
print(elements,"\n")
print(d)

[2, 7, 6, 5, 8, 9, 3, 2, 1] 

[[2 2 1]
 [3 7 6]
 [5 8 9]]


In [34]:
# a = int(input("enter arrya size: "))
# for i in a:
#     i-=a
#     print(i)
# elements = input(f"Enter exactly {a} numbers separated by space:{i} ").split()

# elements = [int(x) for x in elements if x.strip() != '']
# g = np.array(elements)
# print(g)

import numpy as np

a = int(input("Enter array size: "))

while True:
    elements = input(f"Enter exactly {a} numbers separated by space: ").split()
    elements = [x for x in elements if x.strip() != '']
    count = len(elements)
    if count < a:
        print(f"You entered {count} numbers. {a - count} more needed. Try again.")
    elif count > a:
        print(f"You entered {count} numbers. Remove {count - a} numbers. Try again.")
    else:
        elements = [int(x) for x in elements]
        g = np.array(elements)
        print("Your array:", g)
        break

Your array: [1 2 3 4 5]
